// Neon Lounge design tokens — mirrors the Stitch project config so the app
// matches the screen mockups in /stitch.
/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-tint": "#ecb1ff",
        "on-primary": "#520070",
        "secondary-fixed-dim": "#ffb1c4",
        "on-secondary-fixed-variant": "#8f0044",
        "primary-fixed": "#f9d8ff",
        "surface-container-highest": "#343440",
        error: "#ffb4ab",
        "outline-variant": "#514254",
        "on-secondary-container": "#590028",
        "primary-fixed-dim": "#ecb1ff",
        "on-error-container": "#ffdad6",
        background: "#12121d",
        "tertiary-fixed": "#63f7ff",
        "secondary-fixed": "#ffd9e1",
        "on-primary-fixed": "#320046",
        "on-secondary": "#65002e",
        "on-tertiary-container": "#000606",
        surface: "#12121d",
        "surface-variant": "#343440",
        "surface-bright": "#383845",
        "surface-dim": "#12121d",
        outline: "#9d8ba0",
        "on-primary-container": "#ffffff",
        "inverse-primary": "#9900ce",
        "on-tertiary-fixed-variant": "#004f53",
        "surface-container-lowest": "#0d0d18",
        "on-error": "#690005",
        "surface-container-low": "#1b1a26",
        primary: "#ecb1ff",
        "tertiary-fixed-dim": "#00dce5",
        "primary-container": "#bf00ff",
        "surface-container": "#1f1e2a",
        tertiary: "#00dce5",
        "secondary-container": "#ff4a8d",
        "on-tertiary-fixed": "#002021",
        "on-surface": "#e3e0f1",
        "on-surface-variant": "#d5c0d7",
        "inverse-on-surface": "#302f3b",
        "error-container": "#93000a",
        "surface-container-high": "#292935",
        secondary: "#ffb1c4",
        "on-primary-fixed-variant": "#75009e",
        "on-tertiary": "#003739",
        "on-secondary-fixed": "#3f001a",
        "on-background": "#e3e0f1",
        "inverse-surface": "#e3e0f1",
        "tertiary-container": "#00848a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        base: "8px",
        sm: "12px",
        gutter: "16px",
        md: "24px",
        lg: "48px",
        xl: "80px",
        "margin-desktop": "40px",
        "margin-mobile": "20px",
      },
      fontFamily: {
        "headline-lg": ["Montserrat", "sans-serif"],
        "display-lg": ["Montserrat", "sans-serif"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "headline-lg-mobile": ["Montserrat", "sans-serif"],
        "headline-md": ["Montserrat", "sans-serif"],
        "body-lg": ["Hanken Grotesk", "sans-serif"],
        "body-md": ["Hanken Grotesk", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "display-lg": [
          "48px",
          { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "900" },
        ],
        "label-caps": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "700" },
        ],
        "headline-lg-mobile": ["28px", { lineHeight: "34px", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
